### PR TITLE
upgrade uboot to v2024.01

### PR DESCRIPTION
**Pull request by svenrademakers**

### CODE REVIEW

**Comment by dgdonovan** [comment]
Looks good so far. With this commit (and the previous v2.0.5-35-related commits), I am able to apply my minor customizations and build the firmware without the issue of bmcd aborting on startup (pin controller). I have a few nits with the web UI, but those can wait a bit.

**Comment by svenrademakers** [comment]
@dgdonovan Thanks for testing! could you elaborate what "aborting" problems you see?

 i agree there are still a lot of loose ends in the UI. Would be really nice to get them out of the way at some point

**Comment by dgdonovan** [comment]
I'll get the precise output from bmcd. It was complaining about not being able to find a file. I was about to start looking at doing a standalone bmcd build with debug to isolate the issue.

**Comment by svenrademakers** [comment]
@dgdonovan, just so you are aware, I fixed an issue recently that affected the bmcd.bin being cleared. see: #191

**Comment by dgdonovan** [comment]
Yes. I saw that commit and can confirm the issue was fixed by it. I don't believe that bug was the cause of bmcd failing to start. The three errors emitted mentioned gpiod, pin controller and file not found.

**Pull request merged**
