### PR TITLE
Add userspace-manageable regulators and GPIOs entries

### LINKED ISSUE #10: Let Linux manage ATX power and node VRMs through its own power management system?
The Linux power management subsystem has the ability to manage power regulators connected to GPIO pins. By creating `regulator-fixed` nodes in the device tree, we can have Linux itself manage ATX and VRM power state. Linux's PM code is also dependency-aware and can understand that the ATX power is a prerequisite for bringing up node VRMs, etc.

This would simplify the BMC daemon's power management, which would only need to request that power be supplied to a given node: Linux takes care of powering up the necessary upstream regulator(s) and refcounting so that power is not disabled when it's still needed.

This also allows the BMC daemon to be restarted/upgraded while the nodes are powered up and in use, since the initialization of the power management GPIOs is no longer the BMC daemon's responsibility.

### PR DESCRIPTION
**Pull request by CFSworks**
These commits claim even more GPIOs (22 more) in the name of kernelspace.

The necessary drivers are also backported from future versions of Linux. We start to see why I really want to get on a 6.x kernel. :)

Power management is a lot simpler: ATX power does not need to be managed in userspace, and node power can be turned on and off by writing `enabled` or `disabled` to the relevant `/sys/bus/platform/devices/node#-power/state` file. The kernel makes these writes blocking, to allow appropriate time for the regulators to come up. I recommend also using an asynchronous semaphore for `enabled` writes: bringing up a VRM often involves a fair amount of inrush current, so a limit to ensure only one VRM is coming up at a time would help control the peak current (and go easy on people's Pico-PSUs).

The aggregated GPIOs are also preferred: I don't know if a future Turing Pi 2 hardware revision will move GPIOs around, but I want the hardware folks to have that option. Having the GPIOs aggregated on a virtual device controlled by the devicetree means that a board revision would require only an updated devicetree, with (hopefully) no coordination with userspace required.

The only GPIOs not claimed now are related to USB signals routing. I hope to have a nice sysfs/kernel interface for this soon, but for now userspace will need to manage it manually.

Also, I am not 100% sure this PR belongs on `master` -- I see the breaking changes right now are happening on `feature/flash_cm4`. Just put it wherever you think it belongs!

Fixes #10

### CODE REVIEW

**Comment by svenrademakers** [comment]
+1 for the GPIO aggregate, you beat me to it ;) 

> The kernel makes these writes blocking, to allow appropriate time for the regulators to come up. I recommend also 
/using an asynchronous semaphore for enabled writes
just so I understand your comment, do you mean ramping up the VRM is blocking but you could still enable them all in parallel?

As you mentioned, submitting this to master would break it, therefore the feature/flash_cm4 branch is a better choice. However, I want to propose that we don't merge it to the feature branch until the feature branch is merged to master. (i expect this will be end of this week). My main motivation for this is to stop the feature creep on that branch. 
We can then nicely update the implementation to reflect this PR as well on top of it.

I put this PR on my to-do list to review. i will get back to you shortly.

**Comment by CFSworks** [comment]
> just so I understand your comment, do you mean ramping up the VRM is blocking but you could still enable them all in parallel?

Precisely this, yes. Nothing is stopping you from enabling all 4 VRMs in parallel, and the expected thing will happen. I only say to use a semaphore because my intuition says bringing up more than 1 or 2 at a time will likely put more wear on the PSU. My intuition might be completely wrong in this case -- check with the hardware designer for their recommendation. If they say bringing up all 4 at once is completely OK then we should do that.

**Comment by ruslashev** [comment]
> The necessary drivers are also backported from future versions of Linux. We start to see why I really want to get on a 6.x kernel. :)

While I'd also really like to see this, and despite some mainlining efforts [[1]](https://lore.kernel.org/linux-sunxi/20221231231429.18357-1-samuel@sholland.org/T/) [[2]](https://lore.kernel.org/linux-arm-kernel/20230106010155.26868-1-andre.przywara@arm.com/T/), I don't see us moving away from Tina Linux, because of drivers like MTD that I'm a bit anxious to port.

**Comment by svenrademakers** [comment]
Refactoring of rust code to accommodate this PR can start when #77 is merged!

**Comment by svenrademakers** [comment]
Testing the changes. there is some regression with USB switching.

i can see the following logging: 

```shell
[    3.551199] usb-port-vbus GPIO handle specifies active low - ignored
[    3.561090] otg-vbus GPIO handle specifies active low - ignored
```
As a test i flipped the logic of usb-port-power,  but unfortunately, i still cannot connect to a node over USB-A.
TBC

**Comment by CFSworks** [comment]
> Testing the changes. there is some regression with USB switching.

Try adding `status = "disabled";` right under (in the same node as) `gpio = <&pio PG 4 GPIO_ACTIVE_LOW>;`

If that fixes it, the problem is most likely because PG4 is being claimed by the kernel so it can manage the USB port power in kernelspace, and that's upsetting the BMC daemon, which wants to update that GPIO line manually. It should instead be writing to `/sys/bus/platform/devices/usb-port-power/state` to manage the USB port 5V line.

**Comment by svenrademakers** [comment]
The code im using is actually moved to the new repo; see https://github.com/turing-machines/tpi_rs/pull/1 for the changes.

> It should instead be writing to /sys/bus/platform/devices/usb-port-power/state to manage the USB port 5V line.

I have already implemented [these changes](https://github.com/turing-machines/tpi_rs/blob/f1fec6ecd6391b24d7db8a29458611520af1ce44/src/middleware/pin_controller.rs#L83), but still no cigar.

It seems regression is going on in general with the gpio pins. For instance the [power-on](https://github.com/turing-machines/tpi_rs/blob/f1fec6ecd6391b24d7db8a29458611520af1ce44/src/middleware/power_controller.rs#L49) command. writing the `node1-power/state` powers on the node as expected, however after setting the enable, the power goes off again. 

i will A/B a power sequence with strace comparing it with master. I want to rule out any mistakes on my end.

**Comment by svenrademakers** [comment]
I debugged the bmc application and i could not spot any problems on ioctl level.
Furthermore the calls are similar. I.e. looking at a power on sequence of node 1:

current version:
```
# init
ioctl(6, GPIO_GET_CHIPINFO_IOCTL, {name="gpiochip0", label="2000000.pinctrl", lines=224}) = 0
...
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=4, lineoffsets=[103, 102, 101, 100], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0, 0, 0, 0], consumer_label=""} => {fd=12}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=4, lineoffsets=[107, 106, 105, 104], flags=GPIOHANDLE_REQUEST_OUTPUT|GPIOHANDLE_REQUEST_ACTIVE_LOW, default_values=[0, 0, 0, 0], consumer_label=""} => {fd=13}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=4, lineoffsets=[96, 116, 117, 118], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0, 0, 0, 0], consumer_label=""} => {fd=14}) = 0

# power on node 1
ioctl(12, GPIOHANDLE_SET_LINE_VALUES_IOCTL, {values=[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]}) = 0
ioctl(13, GPIOHANDLE_SET_LINE_VALUES_IOCTL, {values=[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]}) = 0
ioctl(14, GPIOHANDLE_SET_LINE_VALUES_IOCTL, {values=[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]}) = 0

```
with new device tree:

```
# init
ioctl(6, GPIO_GET_CHIPINFO_IOCTL, {name="gpiochip1", label="nodes", lines=16}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[0], flags=GPIOHANDLE_REQUEST_OUTPUT|GPIOHANDLE_REQUEST_ACTIVE_LOW, default_values=[0], consumer_label=""} => {fd=7}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[1], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=16}) = 0

# power on node1
ioctl(7, GPIOHANDLE_SET_LINE_VALUES_IOCTL, {values=[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]}) = 0
ioctl(16, GPIOHANDLE_SET_LINE_VALUES_IOCTL, {values=[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]}) = 0
```
Note: Ithe file writes are omitted from this strace, i verified manually and the state is set correctly:

``` shell
# cat /sys/bus/platform/devices/node1-power/state
enabled
```
i attached the traces
[dump_gpio_pr.txt](https://github.com/turing-machines/BMC-Firmware/files/11951249/dump_gpio_pr.txt)
[dump_v1.0.2.txt](https://github.com/turing-machines/BMC-Firmware/files/11951251/dump_v1.0.2.txt)

**Comment by CFSworks** [comment]
> current version:
> 
> ```
> # init
> ioctl(6, GPIO_GET_CHIPINFO_IOCTL, {name="gpiochip0", label="2000000.pinctrl", lines=224}) = 0
> ...
> ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=4, lineoffsets=[103, 102, 101, 100], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0, 0, 0, 0], consumer_label=""} => {fd=12}) = 0
> ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=4, lineoffsets=[107, 106, 105, 104], flags=GPIOHANDLE_REQUEST_OUTPUT|GPIOHANDLE_REQUEST_ACTIVE_LOW, default_values=[0, 0, 0, 0], consumer_label=""} => {fd=13}) = 0
> ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=4, lineoffsets=[96, 116, 117, 118], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0, 0, 0, 0], consumer_label=""} => {fd=14}) = 0
> ```
> 
> with new device tree:
> 
> ```
> # init
> ioctl(6, GPIO_GET_CHIPINFO_IOCTL, {name="gpiochip1", label="nodes", lines=16}) = 0
> ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[0], flags=GPIOHANDLE_REQUEST_OUTPUT|GPIOHANDLE_REQUEST_ACTIVE_LOW, default_values=[0], consumer_label=""} => {fd=7}) = 0
> ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[1], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=16}) = 0
> ```

The biggest difference that I'm seeing here is in the lines= number. I'm not sure if leaving the other 3 node-management lines floating is having any adverse effect.

The new "aggregated GPIO" device also takes care of abstracting away the active-low detail (as after all, that might change in future board revisions), so userspace should probably NOT be specifying the `GPIOHANDLE_REQUEST_ACTIVE_LOW` flag.

**Comment by svenrademakers** [comment]
> The biggest difference that I'm seeing here is in the lines= number. I'm not sure if leaving the other 3 node-management lines floating is having any adverse effect.

they are not necessarily floating, they are initialized one at a time instead of groups.

```
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[0], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=7}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[4], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=13}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[8], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=14}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[12], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=15}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[1], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=16}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[5], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=17}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[9], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=18}) = 0
ioctl(6, GPIO_GET_LINEHANDLE_IOCTL, {lines=1, lineoffsets=[13], flags=GPIOHANDLE_REQUEST_OUTPUT, default_values=[0], consumer_label=""} => {fd=19}) = 0
```

> so userspace should probably NOT be specifying the GPIOHANDLE_REQUEST_ACTIVE_LOW flag. 
will update the code, however, it shouldn't change the behavior of the gpiod line. The funny thing is that after removing the active_low request, the red leds now turn on, but my CM4 module is still not turned on. It seems that the enable pin is not working, which is the one of the pins that moved to the aggregator.

**Comment by CFSworks** [comment]
I was able to verify everything manually. Does this process work for you?
```
# ensure bmc daemon is disabled on boot, then reboot
grep bmc /etc/init.d/S99hello.sh
    #bmc &
reboot

# Export and setup the GPIOs for USB and node1 management:
for x in $(seq 192 195) 197 $(seq 400 403); do echo $x > /sys/class/gpio/export; echo out > /sys/class/gpio/gpio$x/direction; done

# Configure USB routing:
echo 1 > /sys/class/gpio/gpio197/value # Z-end to BMC
echo 1 > /sys/class/gpio/gpio195/value # disable USBSW2
echo 0 > /sys/class/gpio/gpio193/value # USBSW1 to node1
echo 0 > /sys/class/gpio/gpio194/value # enable USBSW1

# Turn on node1:
echo 0 > /sys/class/gpio/gpio400/value # disable
echo 1 > /sys/class/gpio/gpio401/value # assert rst
echo 1 > /sys/class/gpio/gpio403/value # assert rpiboot
echo enabled > /sys/bus/platform/devices/node1-power/state # power up
echo 1 > /sys/class/gpio/gpio400/value # enable
echo 0 > /sys/class/gpio/gpio401/value # deassert rst

# Check for its presence:
lsusb
```

In your trace, it looks like you're not doing the `deassert rst` step.
1. dump_gpio_pr.txt:313 shows that line is grabbed as fd=16
2. dump_gpio_pr.txt:408 shows that line is set high

If you're able to do the above manual shell test, could you then try it again with the `deassert rst` step skipped and see if you get the same behavior?

**Comment by svenrademakers** [comment]
Its all working now; the cause of my issues consisted out of 2 things:
- Passing request Active High/Low from userspace seems to inverse again the config inside the gpio driver?? 
  * PORTx_EN pins are declared active low in the dst.
  * Requested active_low from userspace => didnt work.
  * Request active_high did work.

- Reset pin went from Active High to Active Low

**Review by svenrademakers — APPROVED** [review]

**Pull request closed without merging**
