### PR TITLE
Continuous Integration

### PR DESCRIPTION
**Pull request by Randomblock1**
I added GitHub Actions CI to the original firmware repository, but it didn't seem like PRs were really being accepted. In the new blog post, though, CI is listed as a goal... so here it is! It _should_ just work (in theory) since this is forked from the original but it looks like some restructuring was done, so it's a draft until I can 100% confirm it works as intended.

### CODE REVIEW

**Comment by svenrademakers** [comment]
HI @Randomblock1!
Yes there was some restructuring. We also updated the build root version in the meantime. But I don't think there are significant changes in how we build. 
When you're ready, just put it in ready state :)

**Comment by svenrademakers** [comment]
@Randomblock1 , i took the liberty to push your work to master in #63. Let me know if you have concerns on one of my changes. Thanks a lot for contributing much appreciated!

**Comment by Randomblock1** [comment]
The automatic buildroot update workflow doesn't work currently, and it also doesn't have any way to prevent itself from making duplicate PRs. I'd recommend removing it for now until it's fixed. The actual build workflow should be good to go, though.

**Comment by svenrademakers** [comment]
Im not sure this is something we want to automate in a CI job. As your mentioning, maintaining this comes with a cost, which i think will be more than occasionally opening a manual PR. Therefore i will remove the pipeline for now.

**Pull request closed without merging**
